// ... existing code ...
      <div className="container mx-auto py-8 px-2 sm:px-4 bg-offwhite">
// ... existing code ...
          <Card className="p-6 text-center bg-offwhite text-black border border-gray-200 shadow-md">
// ... existing code ...
        <Card className="p-6 flex flex-col sm:flex-row items-center sm:items-start gap-6 bg-offwhite text-black border border-gray-200 shadow-md">
// ... existing code ...
        <Card className="p-6 w-full max-w-md mx-auto sm:mx-0 bg-offwhite text-black border border-gray-200 shadow-md">
// ... existing code ...